version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=compassUol
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
